version: '3'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: pos_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pos
      MYSQL_USER: user_pos
      MYSQL_PASSWORD: password_pos
    volumes:
      - ./docker/db:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3309:3306
    networks:
      - pos-network
  # php-fpm
  php:
    build: ./docker/php/
    container_name: pos_php
    volumes:
      - /Users/tam.truongphi/Desktop/Rinnegan/Source/pos/src:/var/www/html/pos
      - ./php/docker/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    networks:
      - pos-network
  # Webserver
  nginx:
    platform: linux/amd64
    image: nginx:1.21
    container_name: pos_nginx
    depends_on:
      - php
    ports:
      - 30001:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /Users/tam.truongphi/Desktop/Rinnegan/Source/pos/src:/var/www/html/pos
    restart: unless-stopped
    networks:
      - pos-network
networks:
  pos-network:
    driver: bridge