version: '3'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: pos_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pos
      MYSQL_USER: user_pos
      MYSQL_PASSWORD: password_pos
    volumes:
      - ./docker/db:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3309:3306
    networks:
      - pos-network
  # php-fpm
  php:
    platform: linux/amd64
    build:
      context: ./docker/php
    container_name: pos_php
    environment:
      - WEB_ALIAS_DOMAIN=pos.local
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DATE_TIMEZONE=UTC
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=180000
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
#      - PHP_DEBUGGER=1
#      - XDEBUG_MODE=debug
#      - XDEBUG_CLIENT_PORT=9003
#      - XDEBUG_DISCOVER_CLIENT_HOST=false
#      - XDEBUG_IDE_KEY=PHPSTORM
    volumes:
      - /Users/tam.truongphi/Desktop/Rinnegan/Source/pos/src:/app
    restart: unless-stopped
    ports:
      - '3001:80'
    links:
      - db
    depends_on:
      - db
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge